# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Vivado/i2s_playback/i2s_playback.cache/wt [current_project]
set_property parent.project_path C:/Vivado/i2s_playback/i2s_playback.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Vivado/i2s_playback/i2s_playback.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/Digital_Efects.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/EfectCOMPRESSOR.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/sine_package.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/EfectoAUTOWAH.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/sine_package2.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/EfectoCHORUS.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/EfectoDELAY.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/EfectoES.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/EfectoLOOPER.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/EfectoOVERDRIVE.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/EfectoREVERB.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/EfectoREVERB_PARAMETRIZADO.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/EfectoREVERB_test.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/EfectoVIBRATO.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/EfectoWAHWAH.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/Fir_Filter_Autowah.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/LEDs.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/Ruta_datos_FIR_WAH.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/controlador_fir_WAH.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/display_counter.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/project_trunk.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/display_interface.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/i2s_transceiver.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/register.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/sine_wave.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/sine_wave_autowah.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/sine_wave_chorus.vhd
  C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/new/i2s_playback.vhd
}
read_ip -quiet C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]
set_property is_locked true [get_files C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci]

read_ip -quiet C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all c:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]
set_property is_locked true [get_files C:/Vivado/i2s_playback/i2s_playback.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Vivado/i2s_playback/i2s_playback.srcs/constrs_1/new/i2s_playback.xdc
set_property used_in_implementation false [get_files C:/Vivado/i2s_playback/i2s_playback.srcs/constrs_1/new/i2s_playback.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top i2s_playback -part xc7a100tcsg324-1


write_checkpoint -force -noxdef i2s_playback.dcp

catch { report_utilization -file i2s_playback_utilization_synth.rpt -pb i2s_playback_utilization_synth.pb }
